module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "build",
        "ci",
        "chore",
        "revert",
        "wip",
      ],
    ],
    "scope-enum": [
      2,
      "always",
      [
        "T-DISC",
        "T-SETUP",
        "T-QA",
        "T-CI",
        "T-BE-SETUP",
        "T-BE-SEC",
        "T-AUTH-CLERK",
        "T-BE-GAME",
        "T-BE-PAY",
        "T-BE-RANK",
        "T-BE-SUPPORT",
        "T-BE-IA",
        "T-FE-SETUP-SHADCN",
        "T-FE-SETUP-AXIOS",
        "T-FE-SETUP-ZUSTAND",
        "T-FE",
        "T-FE-02",
        "T-FE-03",
        "T-FE-05",
        "T-FE-06",
        "T-FE-07",
        "T-FE-08",
        "T-QA-INT",
        "T-RELEASE",
        "T-IA",
        "T-SEC",
        "T-INFRA",
        "*",
      ], // Agrega aquí los scopes de tus tareas principales (ej. T-XXX)
    ],
    "header-max-length": [2, "always", 100],
    "body-leading-blank": [2, "always"],
    "footer-leading-blank": [2, "always"],
  },
};
